spring.application.name=gym_management_system
spring.docker.compose.enabled=false

spring.profiles.active=prod

api.base.path=/api/v1

spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.jpa.hibernate.naming.physical-strategy=org.java_proj.gym_management_system.common.jpa.PluralPhysicalNamingStrategy