spring:
  datasource:
    url: jdbc:mysql://avnadmin:${AIVEN_DB_PASSWORD}@mysql-319dcd54-tmoe8123-37cd.b.aivencloud.com:27965/gym_management_system_db?ssl-mode=REQUIRED
    username: avnadmin
    password: ${AIVEN_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # Start with only 1 or 2 connections to speed up the boot
      minimum-idle: 1
      maximum-pool-size: 5
      # Increase timeout so it doesn't give up if the cloud is slow
      connection-timeout: 30000
      # Helps skip some initial metadata checks
      initialization-fail-timeout: 0

  main:
    lazy-initialization: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: tmoe8123@gmail.com
    password: jvrvtpokyjusurma
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ZP4g8Nj6QbXWYr2NvG2kXsKcD1HLqEyV
